/// Detect languages by checking for marker files in the given directory.
pub fn detect_languages(path: &std::path::Path) -> Vec<String> {
    let mut langs = std::collections::HashSet::new();

    let python_markers = ["pyproject.toml", "requirements.txt", "setup.py"];
    if python_markers.iter().any(|f| path.join(f).exists()) {
        langs.insert("python");
    }
    if path.join("package.json").exists() {
        langs.insert("typescript");
    }
    if path.join("composer.json").exists() {
        langs.insert("php");
    }
    if path.join("Cargo.toml").exists() {
        langs.insert("rust");
    }

    let mut result: Vec<String> = langs.into_iter().map(|s| s.to_string()).collect();
    result.sort();
    result
}

/// Run `exspec init` in the given directory.
/// Detects languages and writes a minimal `.exspec.toml`.
#[allow(dead_code)]
pub fn run_init(path: &std::path::Path) {
    let langs = detect_languages(path);
    if langs.is_empty() {
        eprintln!(
            "warning: no supported language markers found in {}",
            path.display()
        );
        return;
    }
    let toml = generate_toml(&langs);
    let out = path.join(".exspec.toml");
    std::fs::write(&out, toml).expect("failed to write .exspec.toml");
    println!("Created {}", out.display());
}

/// Generate minimal .exspec.toml content from detected languages.
pub fn generate_toml(languages: &[String]) -> String {
    // Build lang list
    let lang_entries: Vec<String> = languages.iter().map(|l| format!(r#""{l}""#)).collect();
    let lang_list = lang_entries.join(", ");

    // Build ignore list
    let mut ignores = std::collections::HashSet::new();
    for lang in languages {
        match lang.as_str() {
            "python" => {
                ignores.insert(".venv");
                ignores.insert("__pycache__");
            }
            "typescript" => {
                ignores.insert("node_modules");
                ignores.insert("dist");
                ignores.insert(".next");
            }
            "php" => {
                ignores.insert("vendor");
            }
            "rust" => {
                ignores.insert("target");
            }
            _ => {}
        }
    }
    let mut ignore_list: Vec<&str> = ignores.into_iter().collect();
    ignore_list.sort();
    let ignore_entries: Vec<String> = ignore_list.iter().map(|s| format!(r#""{s}""#)).collect();
    let ignore_str = ignore_entries.join(", ");

    format!(
        "# Generated by `exspec init`\n\n[general]\nlang = [{lang_list}]\n\n[paths]\nignore = [{ignore_str}]\n"
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::tempdir;

    // TC-01: pyproject.toml → ["python"]
    #[test]
    fn init_tc01_detect_python_via_pyproject_toml() {
        // Given: tempdir に pyproject.toml を作成
        let dir = tempdir().unwrap();
        fs::write(dir.path().join("pyproject.toml"), "").unwrap();

        // When
        let result = detect_languages(dir.path());

        // Then
        assert_eq!(result, vec!["python".to_string()]);
    }

    // TC-02: package.json → ["typescript"]
    #[test]
    fn init_tc02_detect_typescript_via_package_json() {
        // Given: tempdir に package.json を作成
        let dir = tempdir().unwrap();
        fs::write(dir.path().join("package.json"), "{}").unwrap();

        // When
        let result = detect_languages(dir.path());

        // Then
        assert_eq!(result, vec!["typescript".to_string()]);
    }

    // TC-03: composer.json → ["php"]
    #[test]
    fn init_tc03_detect_php_via_composer_json() {
        // Given: tempdir に composer.json を作成
        let dir = tempdir().unwrap();
        fs::write(dir.path().join("composer.json"), "{}").unwrap();

        // When
        let result = detect_languages(dir.path());

        // Then
        assert_eq!(result, vec!["php".to_string()]);
    }

    // TC-04: Cargo.toml → ["rust"]
    #[test]
    fn init_tc04_detect_rust_via_cargo_toml() {
        // Given: tempdir に Cargo.toml を作成
        let dir = tempdir().unwrap();
        fs::write(dir.path().join("Cargo.toml"), "").unwrap();

        // When
        let result = detect_languages(dir.path());

        // Then
        assert_eq!(result, vec!["rust".to_string()]);
    }

    // TC-05: package.json + pyproject.toml → ["python", "typescript"] (アルファベット順)
    #[test]
    fn init_tc05_detect_multiple_languages_sorted() {
        // Given: tempdir に package.json と pyproject.toml を作成
        let dir = tempdir().unwrap();
        fs::write(dir.path().join("package.json"), "{}").unwrap();
        fs::write(dir.path().join("pyproject.toml"), "").unwrap();

        // When
        let result = detect_languages(dir.path());

        // Then: アルファベット順
        assert_eq!(result, vec!["python".to_string(), "typescript".to_string()]);
    }

    // TC-06: generate_toml(["python"]) → lang = ["python"] を含む
    #[test]
    fn init_tc06_generate_toml_single_language() {
        // Given
        let langs = vec!["python".to_string()];

        // When
        let result = generate_toml(&langs);

        // Then
        assert!(
            result.contains(r#"lang = ["python"]"#),
            "Expected result to contain `lang = [\"python\"]`, got: {result}"
        );
    }

    // TC-07: 空ディレクトリ → 空 Vec
    #[test]
    fn init_tc07_empty_directory_returns_empty_vec() {
        // Given: 空の tempdir
        let dir = tempdir().unwrap();

        // When
        let result = detect_languages(dir.path());

        // Then
        assert!(result.is_empty(), "Expected empty Vec, got: {result:?}");
    }

    // TC-08: generate_toml(["python", "typescript"]) → lang = ["python", "typescript"] かつ .venv と node_modules を含む
    #[test]
    fn init_tc08_generate_toml_multiple_languages_with_ignores() {
        // Given
        let langs = vec!["python".to_string(), "typescript".to_string()];

        // When
        let result = generate_toml(&langs);

        // Then
        assert!(
            result.contains(r#"lang = ["python", "typescript"]"#),
            "Expected result to contain `lang = [\"python\", \"typescript\"]`, got: {result}"
        );
        assert!(
            result.contains(".venv"),
            "Expected result to contain `.venv`, got: {result}"
        );
        assert!(
            result.contains("node_modules"),
            "Expected result to contain `node_modules`, got: {result}"
        );
    }
}
